server:
  port: 8383
  servlet:
    encoding:
      charset: UTF-8
    session:
      timeout: 60m

spring:
  application:
    name: odockodock-api

  config:
    import: optional:file:.env[.properties]

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DATASOURCE_HOST}:${DATASOURCE_PORT}/${DATASOURCE_NAME}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    hikari:
      maximum-pool-size: 10

  jpa:
    hibernate:
      ddl-auto: update      # ?? validate, create, none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false     # API ?? ???

  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true

  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}

jwt:
  secret: ${JWT_SECRET}
  expiration-time: ${JWT_EXPIRATION}

external:
  api:
    library-key: ${LIBRARY_API_KEY}
    consumer-key: ${CONSUMER_KEY}
    consumer-secret: ${CONSUMER_SECRET_KEY}
    base-url: https://korea-webtoon-api-cc7dda2f0d77.herokuapp.com/